version: '3.4'

services:
  montrium.connect.pdf.web:
    image: montriumconnectpdfweb:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_montrium.connect.pdf.web$
    volumes:
      - C:\Users\sbashar\Connect\src\Montrium.Connect.PDF.Web:/app
      - C:\Users\sbashar\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_montrium.connect.pdf.web$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_montrium.connect.pdf.web$ bin/Debug/netcoreapp2.1/Montrium.Connect.PDF.Web.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
